from mathml_to_latex import clean_html_and_convert_mathml
from IPython.display import Markdown, display

if __name__ == '__main__':

    html_snippet ="""<div><div><span class='az-text'>گزینه ۱‏ پاسخ صحیح است. فقط مورد </span><span class='az-text'>«</span><span class='az-text'>ت</span><span class='az-text'>»</span><span class='az-text'> درست است.</span></div><div><span class='az-text'>بررسی عبارت</span><span>&zwnj;</span><span class='az-text'>های نادرست:</span></div><div><span class='az-text'>الف) به</span><span>&zwnj;</span><span class='az-text'>طور مثال فلز &zwnj;آلومینیم در مجاورت با اکسیژن اکسید می</span><span>&zwnj;</span><span class='az-text'>شود، اما در برابر خوردگی مقاوم است.</span></div><div><span class='az-text'>ب) محلول اکسید اکثر فلزها در &zwnj;آب خاصیت </span><u><span class='az-text'>بازی</span></u><span class='az-text'> دارد.</span></div><div><span class='az-text'>پ) </span><span class='az-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mmultiscripts><mrow><mi>CS</mi></mrow><mrow><mn>۲</mn></mrow></mmultiscripts></mstyle></math></span><span class='az-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\">   </mstyle></math></span><span class='az-text'>، کربن دی</span><span>&zwnj;</span><span class='az-text'>سولفید نام دارد.</span></div></div>"""
    print("------------------------------")
    result = clean_html_and_convert_mathml(html_snippet)
    # print(result)
    display(Markdown(result))
    html_snippet ="""<div><div><span class='rz-text'>۰‏۱‏ گرم از &zwnj;آلیاژ &zwnj;آلومینیم و نقره در مقدار کافی از محلول هیدروکلریک اسید با غلظت </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mn>۵</mn> <mi>g</mi><mo>.</mo><mrow><msup><mrow><mi>L</mi></mrow><mrow><mrow><mi>−</mi></mrow><mrow><mn>١</mn></mrow></mrow></msup></mrow></mstyle></math></span><span class='rz-text'> انداخته شده است. اگر </span><span class='rz-text'>در پایان واکنش، ۳‏ لیتر گاز هیدروژن در شرایطی که چگالی &zwnj;آن </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mn>۰</mn> <mi>⁄</mi> <mi>۰۸</mi></mstyle></math></span><span class='rz-text'> گرم بر لیتر است، &zwnj;آزاد شود، درصد جرمی فلز </span><span class='rz-text'>نقره در این &zwnj;آلیاژ کدام است و برای انجام کامل این واکنش چند لیتر از محلول این اسید لازم است؟</span></div><div><span class='rz-text'>(گزینه</span><span>&zwnj;</span><span class='rz-text'>ها را از راست به چپ بخوانید. نقره با اسید واکنش نمی</span><span>&zwnj;</span><span class='rz-text'>دهد. </span></div><div class='rz-align-left'><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mi>H</mi> <mo>= </mo><mn>١</mn> <mo>, </mo><mi>Al</mi> <mo>= </mo><mi>۲۷</mi> <mo>, </mo><mi>C</mi> <mo>= </mo><mi>۳۵</mi> <mi>⁄</mi> <mn>۵</mn> <mo>, </mo><mi>Ag</mi> <mo>= </mo><mtext>١۰۸</mtext> <mo>: </mo><mi>g</mi><mo>.</mo><mrow><msup><mrow><mi>mol</mi></mrow><mrow><mrow><mi>−</mi></mrow><mrow><mn>١</mn></mrow></mrow></msup></mrow></mstyle></math></span><span>)</span></div><div class='rz-align-left'><span class='rz-text'>(واکنش موازنه شود.)  </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mi>Al</mi> <mn>(</mn><mi>s</mi><mn>)</mn> <mo>+ </mo><mi>HCl</mi> <mn>(</mn><mi>aq</mi><mn>)</mn> <mo>→</mo><mmultiscripts><mrow><mi>AlCl</mi></mrow><mrow><mn>۳</mn></mrow></mmultiscripts> <mn>(</mn><mi>aq</mi><mn>)</mn> <mo>+ </mo><mmultiscripts><mrow><mi>H</mi></mrow><mrow><mn>۲</mn></mrow></mmultiscripts> <mn>(</mn><mi>g</mi><mn>)</mn></mstyle></math></span></div></div>"""
    print("--------------x----------------")
    result = clean_html_and_convert_mathml(html_snippet)
    # print(result)
    display(Markdown(result))
    html_snippet ="""<div><div><span class='rz-text'>۰‏۰‏۵‏ میلی</span><span>&zwnj;</span><span class='rz-text'>لیتر محلول پتاسیم هیدروکسید با درصد جرمی ۸‏۲‏ درصد و چگالی </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mn>١</mn> <mi>⁄</mi> <mn>۲</mn></mstyle></math></span><span class='rz-text'> گرم بر میلی</span><span>&zwnj;</span><span class='rz-text'>لیتر را با افزودن </span><span class='rz-text'>مقداری &zwnj;آب رقیق می</span><span>&zwnj;</span><span class='rz-text'>کنیم. اگر در محلول حاصل غلظت یون پتاسیم برابر </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mtext>١١۷۰</mtext> <mi>ppm</mi></mstyle></math></span><span class='rz-text'> باشد، کدام گزینه درباره</span><span>&zwnj;</span><span class='rz-text'>ی &zwnj;آن </span><span class='rz-text'>درست است؟ (چگالی محلول نهایی را </span><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mn>١</mn> <mi>g</mi><mo>.</mo><mrow><msup><mrow><mi>mL</mi></mrow><mrow><mrow><mi>−</mi></mrow><mrow><mn>١</mn></mrow></mrow></msup></mrow></mstyle></math></span><span class='rz-text'> درنظر بگیرید.)</span></div><div><span class='rz-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mn>(</mn><mi>H</mi> <mo>= </mo><mn>١</mn> <mo>, </mo><mi>O</mi> <mo>= </mo><mtext>١۶</mtext> <mo>, </mo><mi>K</mi> <mo>= </mo><mi>۳۹</mi> <mo>: </mo><mi>g</mi><mo>.</mo><mrow><msup><mrow><mi>mol</mi></mrow><mrow><mrow><mi>−</mi></mrow><mrow><mn>١</mn></mrow></mrow></msup></mrow><mn>)</mn></mstyle></math></span><span class='rz-text'> (چگالی &zwnj;آب را یک گرم بر میلی</span><span>&zwnj;</span><span class='rz-text'>لیتر درنظر بگیرید.)</span></div></div>"""
    print("------------------------------")
    result = clean_html_and_convert_mathml(html_snippet)
    # print(result)
    display(Markdown(result))
    html_snippet ="""<div><div><span class='az-text'>گزینه ۳‏ پاسخ صحیح است. دلیل نادرستی سایر گزینه</span><span>&zwnj;</span><span class='az-text'>ها:</span></div><div><span class='az-text'>گزینهٔ ۱‏: در هنگام رعد و برق، از واکنش گازهای نیتروژن و اکسیژن با یکدیگر اکسیدهای نیتروژن تولید می</span><span>&zwnj;</span><span class='az-text'>شوند.</span></div><div><span class='az-text'>گزینهٔ ۲‏: اوزون در لایهٔ استراتوسفر نقش مفید و محافظتی دارد.</span></div><div><span class='az-text'>گزینهٔ ۴‏: در تروپوسفر از واکنش </span><span class='az-formula'><math  display=\"inline\" displaystyle=\"true\"><mstyle displaystyle=\"true\" dir=\"ltr\"><mmultiscripts><mrow><mi>NO</mi></mrow><mrow><mn>۲</mn></mrow></mmultiscripts> <mn>(</mn><mi>g</mi><mn>)</mn> <mo>+ </mo><mmultiscripts><mrow><mi>O</mi></mrow><mrow><mn>۲</mn></mrow></mmultiscripts> <mn>(</mn><mi>g</mi><mn>)</mn>  <mrow><munderover><mo>→</mo><mrow> </mrow><mrow><mtext>نور خورشید</mtext></mrow></munderover></mrow><mpadded width=\"3px\" /><mi>NO</mi> <mn>(</mn><mi>g</mi><mn>)</mn> <mo>+ </mo><mmultiscripts><mrow><mi>O</mi></mrow><mrow><mn>۳</mn></mrow></mmultiscripts> <mn>(</mn><mi>g</mi><mn>)</mn></mstyle></math></span><span class='az-text'>، گاز اوزون تولید </span><span class='az-text'>می</span><span>&zwnj;</span><span class='az-text'>شود.</span></div></div>"""
    print("------------------------------")
    result = clean_html_and_convert_mathml(html_snippet)
    # print(result)
    display(Markdown(result))